/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface DatesDisplay {}
}

declare global {


  interface HTMLDatesDisplayElement extends Components.DatesDisplay, HTMLStencilElement {}
  var HTMLDatesDisplayElement: {
    prototype: HTMLDatesDisplayElement;
    new (): HTMLDatesDisplayElement;
  };
  interface HTMLElementTagNameMap {
    'dates-display': HTMLDatesDisplayElement;
  }
}

declare namespace LocalJSX {
  interface DatesDisplay {}

  interface IntrinsicElements {
    'dates-display': DatesDisplay;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'dates-display': LocalJSX.DatesDisplay & JSXBase.HTMLAttributes<HTMLDatesDisplayElement>;
    }
  }
}


